import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {run,readJson,writeJson,sha256} from '../lib/system.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'pi-config-smoke-'));
const root=path.join(temporary,'platform with spaces'),agentDir=path.join(temporary,'agent'),binDir=path.join(temporary,'bin');
const args=[path.join(repo,'install.mjs'),'--root',root,'--agent-dir',agentDir,'--bin-dir',binDir,'--no-path'];
await run(process.execPath,args,{timeout:1800000});
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'main','--version']);
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'models']);
await run(process.execPath,['--test',...['patches','models','glm-wire','native-search-wire','claude-effort-wire','rewind-session','subagent-markdown'].map(name=>path.join(repo,`tests/${name}.test.mjs`))],{env:{...process.env,PI_CONFIG_TEST_ROOT:root}});
for(const profile of ['main'])await run(process.execPath,[path.join(repo,'tests/profile-integration.mjs'),root,profile]);
for(const profile of ['main'])await run(process.execPath,[path.join(repo,'tests/agent-integration.mjs'),root,profile]);
const settingsPath=path.join(agentDir,'settings.json');
const settings=readJson(settingsPath);
settings.theme='rose-pine-dawn';writeJson(settingsPath,settings);
const statePath=path.join(root,'install-state.json'),prior=readJson(statePath);
const unused=path.join(root,'assets/unused-resource.json');
writeJson(unused,{fixture:'managed resource'});prior.files[unused]=sha256(fs.readFileSync(unused));
const custom=path.join(root,'profiles/background/optional.json');
writeJson(custom,{fixture:'default'});prior.files[custom]=sha256(fs.readFileSync(custom));
writeJson(custom,{fixture:'user edit'});writeJson(statePath,prior);
const secret=path.join(root,'secrets/provider.env');
fs.mkdirSync(path.dirname(secret),{recursive:true});fs.writeFileSync(secret,'PROVIDER_API_KEY=synthetic-preservation-fixture\n',{mode:0o600});
const secretBefore=fs.readFileSync(secret);
const auth=path.join(agentDir,'auth.json');const authBefore=fs.readFileSync(auth);
await run(process.execPath,args);
assert.equal(readJson(settingsPath).theme,'rose-pine-dawn');
assert.equal(fs.existsSync(unused),false);
assert.equal(readJson(custom).fixture,'user edit');
assert.deepEqual(fs.readFileSync(secret),secretBefore);
await run(process.execPath,[path.join(repo,'tests/agent-integration.mjs'),root,'main']);
assert.deepEqual(fs.readFileSync(auth),authBefore);
const state=readJson(path.join(root,'install-state.json'));assert.equal(Object.keys(state.sources).length,3);
assert.equal(fs.existsSync(path.join(root,'.install.lock')),false);
console.log('PASS: cài sạch, một runtime Pi, slash workflows, auth/permission, chạy lại giữ tùy chỉnh và secret giả.');
console.log(`Fixture: ${root}`);
if(process.env.GITHUB_ENV){
  fs.appendFileSync(process.env.GITHUB_ENV,`PI_CONFIG_SMOKE_ROOT=${root}\nPI_CONFIG_SMOKE_AGENT_DIR=${agentDir}\nPI_CONFIG_SMOKE_BIN_DIR=${binDir}\n`);
}
