import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {run,readJson,writeJson,sha256} from '../lib/system.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'pi-config-smoke-'));
const root=path.join(temporary,'platform with spaces'),agentDir=path.join(temporary,'agent'),binDir=path.join(temporary,'bin');
const args=[path.join(repo,'install.mjs'),'--root',root,'--agent-dir',agentDir,'--bin-dir',binDir,'--no-path'];
await run(process.execPath,args,{timeout:1800000});
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'main','--version']);
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'goal','--version']);
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'models']);
await run(process.execPath,['--test',path.join(repo,'tests/patches.test.mjs'),path.join(repo,'tests/compat-models.test.mjs'),path.join(repo,'tests/glm-wire.test.mjs')],{env:{...process.env,PI_CONFIG_TEST_ROOT:root}});
for(const profile of ['main','goal','background','advisor'])await run(process.execPath,[path.join(repo,'tests/profile-integration.mjs'),root,profile]);
for(const profile of ['main','goal'])await run(process.execPath,[path.join(repo,'tests/agent-integration.mjs'),root,profile]);
const settingsPath=path.join(agentDir,'settings.json');
const settings=readJson(settingsPath);
// Emulate an owned dispatcher from the previous release plus a user-edited theme.
const oldExtension=path.join(root,'assets/extensions/pi-dispatch-router/index.ts');
fs.mkdirSync(path.dirname(oldExtension),{recursive:true});fs.writeFileSync(oldExtension,'throw new Error("retired extension must never load");\n');
settings.extensions.push(oldExtension);
const prior=readJson(path.join(root,'install-state.json'));
prior.files[oldExtension]=sha256(fs.readFileSync(oldExtension));
prior.files[settingsPath]=sha256(JSON.stringify(settings,null,2)+'\n');
settings.theme='rose-pine-dawn';writeJson(settingsPath,settings);
const oldRole=path.join(agentDir,'agents/worker-glm.md');
fs.writeFileSync(oldRole,'retired role fixture');prior.files[oldRole]=sha256(fs.readFileSync(oldRole));
const oldRoleAsset=path.join(root,'assets/roles/worker-glm.md');
fs.writeFileSync(oldRoleAsset,'retired asset fixture');prior.files[oldRoleAsset]=sha256(fs.readFileSync(oldRoleAsset));
const oldPolicy=path.join(agentDir,'routing.json');writeJson(oldPolicy,{version:2,mode:'manual'});
prior.files[oldPolicy]=sha256(fs.readFileSync(oldPolicy));
const inactiveFile=path.join(root,'profiles/background/subagents.json');
writeJson(inactiveFile,{fixture:'unused previous default'});prior.files[inactiveFile]=sha256(fs.readFileSync(inactiveFile));
const customInactiveFile=path.join(root,'profiles/background/advisor.json');
writeJson(customInactiveFile,{fixture:'previous default'});prior.files[customInactiveFile]=sha256(fs.readFileSync(customInactiveFile));
writeJson(customInactiveFile,{fixture:'user edited, must preserve'});
writeJson(path.join(root,'install-state.json'),prior);
const privateConfig=path.join(agentDir,'compact-adviser.json');
assert.equal(fs.existsSync(privateConfig),false);
// A pre-existing retired credential belongs to the user; reinstall must not delete it.
fs.writeFileSync(privateConfig,JSON.stringify({typesafeApiKey:'synthetic-secret-preservation-only'}));
const auth=path.join(agentDir,'auth.json');const authBefore=fs.readFileSync(auth);
await run(process.execPath,args);
assert.equal(readJson(settingsPath).theme,'rose-pine-dawn');
assert.ok(!readJson(settingsPath).extensions.includes(oldExtension));
assert.equal(fs.existsSync(oldExtension),false);assert.equal(fs.existsSync(oldPolicy),false);
assert.equal(fs.existsSync(oldRole),false);assert.equal(fs.existsSync(oldRoleAsset),false);
assert.equal(fs.existsSync(inactiveFile),false);assert.equal(readJson(customInactiveFile).fixture,'user edited, must preserve');
await run(process.execPath,[path.join(repo,'tests/agent-integration.mjs'),root,'main']);
assert.equal(readJson(settingsPath).packages.some(p=>p.endsWith('compact-adviser')),false);
assert.equal(readJson(privateConfig).typesafeApiKey,'synthetic-secret-preservation-only');
assert.deepEqual(fs.readFileSync(auth),authBefore);
const state=readJson(path.join(root,'install-state.json'));assert.equal(Object.keys(state.sources).length,3);
assert.equal(fs.existsSync(path.join(root,'.install.lock')),false);
console.log('PASS: cài sạch, hai runtime, bốn profile, auth/permission, chạy lại giữ tùy chỉnh và secret giả.');
console.log(`Fixture: ${root}`);
if(process.env.GITHUB_ENV){
  fs.appendFileSync(process.env.GITHUB_ENV,`PI_CONFIG_SMOKE_ROOT=${root}\nPI_CONFIG_SMOKE_AGENT_DIR=${agentDir}\nPI_CONFIG_SMOKE_BIN_DIR=${binDir}\n`);
}
