import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {run,readJson} from '../lib/system.mjs';
const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'pi-config-smoke-'));
const root=path.join(temporary,'platform with spaces'),agentDir=path.join(temporary,'agent'),binDir=path.join(temporary,'bin');
const args=[path.join(repo,'install.mjs'),'--root',root,'--agent-dir',agentDir,'--bin-dir',binDir,'--no-path'];
await run(process.execPath,args);
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'main','--version']);
await run(process.execPath,[path.join(root,'bin/launch.mjs'),'goal','--version']);
await run(process.execPath,['--test',path.join(repo,'tests/patches.test.mjs')],{env:{...process.env,PI_CONFIG_TEST_ROOT:root}});
for(const profile of ['main','goal','background','advisor'])await run(process.execPath,[path.join(repo,'tests/profile-integration.mjs'),root,profile]);
const settingsPath=path.join(agentDir,'settings.json');
const settings=readJson(settingsPath);settings.theme='rose-pine-dawn';fs.writeFileSync(settingsPath,JSON.stringify(settings,null,2)+'\n');
const privateConfig=path.join(agentDir,'compact-adviser.json');
const adviser=readJson(privateConfig);adviser.typesafeApiKey='synthetic-secret-preservation-only';fs.writeFileSync(privateConfig,JSON.stringify(adviser));
const auth=path.join(agentDir,'auth.json');const authBefore=fs.readFileSync(auth);
await run(process.execPath,args);
assert.equal(readJson(settingsPath).theme,'rose-pine-dawn');
assert.equal(readJson(privateConfig).typesafeApiKey,'synthetic-secret-preservation-only');
assert.deepEqual(fs.readFileSync(auth),authBefore);
const state=readJson(path.join(root,'install-state.json'));assert.equal(Object.keys(state.sources).length,3);
assert.equal(fs.existsSync(path.join(root,'.install.lock')),false);
console.log('PASS: cài sạch, hai runtime, bốn profile, auth/permission, chạy lại giữ tùy chỉnh và secret giả.');
console.log(`Fixture: ${root}`);
